"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var getAllOrders_1 = require("../controllers/orders/getAllOrders");
var getSingleOrder_1 = require("../controllers/orders/getSingleOrder");
var deleteOrder_1 = require("../controllers/orders/deleteOrder");
var addOrder_1 = require("../controllers/orders/addOrder");
var updateOrder_1 = require("../controllers/orders/updateOrder");
var validate_1 = require("../middlewares/validate");
var orderSchema_1 = require("../schemas/orderSchema");
var checkAuth_1 = require("../middlewares/checkAuth");
var checkPermissions_1 = require("../middlewares/checkPermissions");
var role_1 = require("../utils/role");
var checkRoles_1 = require("../middlewares/checkRoles");
var ordersRouter = (0, express_1.Router)();
ordersRouter.get('/', checkAuth_1.checkAuth, (0, checkRoles_1.checkRoles)(role_1.ROLE.ADMIN), (0, checkPermissions_1.checkPermission)("READ"), getAllOrders_1.getAllOrders);
ordersRouter.get('/:orderId', checkAuth_1.checkAuth, getSingleOrder_1.getSingleOrder);
ordersRouter.post('/', (0, validate_1.validate)(orderSchema_1.orderSchema), checkAuth_1.checkAuth, addOrder_1.addOrder);
ordersRouter.patch("/:orderId", (0, validate_1.validate)(orderSchema_1.orderSchema), checkAuth_1.checkAuth, updateOrder_1.updateOrder);
ordersRouter.delete("/:orderId", checkAuth_1.checkAuth, deleteOrder_1.deleteOrder);
exports.default = ordersRouter;
