"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var users_1 = require("../controllers/users");
var validate_1 = require("../middlewares/validate");
var userSchema_1 = require("../schemas/userSchema");
var emailChecker_1 = require("../middlewares/emailChecker");
var checkAuth_1 = require("../middlewares/checkAuth");
var checkRoles_1 = require("../middlewares/checkRoles");
var role_1 = require("../utils/role");
var passport_1 = require("passport");
var checkPermissions_1 = require("../middlewares/checkPermissions");
var usersRouter = express_1.default.Router();
usersRouter.get("/", users_1.default.getAllUsers);
usersRouter.get("/profile/:userId", checkAuth_1.checkAuth, users_1.default.getSingleUser);
usersRouter.put("/:userId", (0, validate_1.validate)(userSchema_1.updateUserSchema), emailChecker_1.emailChecker, checkAuth_1.checkAuth, (0, checkRoles_1.checkRoles)(role_1.ROLE.ADMIN), (0, checkPermissions_1.checkPermission)("UPDATE"), users_1.default.updateUser);
usersRouter.delete("/:userId", checkAuth_1.checkAuth, (0, checkRoles_1.checkRoles)(role_1.ROLE.ADMIN), (0, checkPermissions_1.checkPermission)("DELETE"), users_1.default.deleteUser);
usersRouter.post("/signup", emailChecker_1.emailChecker, users_1.default.signUp);
usersRouter.post("/login", users_1.default.logIn);
usersRouter.post("/login-google", passport_1.default.authenticate("google-id-token", { session: false }), users_1.default.googleLogIn);
exports.default = usersRouter;
